export const GET_TOGGLE_NAVIGATION = "GET_TOGGLE_NAVIGATION";

export const GET_DARKMODE = "GET_DARKMODE";
export const SET_DARKMODE = "SET_DARKMODE";

export const SET_NAVIGATION_CONTENT = "SET_NAVIGATION_CONTENT";
